---
title: "First Year Exam - Question 15"
author: "Taylor F. (A59010460)"
date: "7/17/2022"
output:
  pdf_document: default
  html_document: default
---


```{r}
#load in necessary packages
library("ggplot2")
library("lubridate")
library("tidyverse")
library("dplyr")
```

```{r}
#read in csv
var_data <- read.csv("covid19_variants.csv")
#remove total and other
var_data_no_total <- subset(var_data, variant_name != "Total" & variant_name != "Other")
#extract relevant columns
data <- var_data_no_total[, c("date", "variant_name", "percentage")]
#format date
data$date <- ymd(data$date)
```


```{r}
#df <- var_data_no_total %>% select(date, variant_name) %>% gather(key = "variant_name", value = "percentage", -date)
#head(df)
```


```{r}
#make plot
var_plot <- ggplot(data) + aes(date, percentage, col = variant_name) + geom_line(group = 1) +  labs(x="Date", y="Percent of Sequenced Specimens",
       title="COVID-19 Variants in California",
       caption="Data source: <https://www.cdph.ca.gov/>") + scale_colour_discrete(name="Variant")
var_plot
```



